validates not allow deficient source
philippinedev/budgetting pull request #131
Opened 2021-10-04 15:26 UTC by abe-phdev

2021-10-04 15:29 UTC, rusbal commented on app/models/transaction.rb
> +  def amount_sufficiency
Change `amount_sufficiency` to `source_sufficiency`

2021-10-04 15:33 UTC, rusbal requested changes
Good work but not enough.  The problem is race condition where more than one transaction is being created at the same time.
Let's mob program on this tomorrow.

2021-10-05 03:07 UTC, rusbal requested changes
As discussed

```ruby
  # Save as app/models/not_enough_source.rb
  class NotEnoughSource < StandardError
  end

  def do_the_transfer
    transfer_now
  rescue NotEnoughSource => error
    errors.add(:source_account_id, error.message)
  end

  def transfer_now
    ActiveRecord::Base.transaction do
      save_transfer
      source = basahin_muli_sa_db_after_ng_save

      if source.negative?
        raise NotEnoughSource.new "Insufficient funds on source account"
      end
    end
  end
```

2021-10-05 06:37 UTC, rusbal commented
As discussed
```ruby
  def create
    ActiveRecord::Base.transaction do

      #-------- BEGIN (All of the below will be undone if not enough source)  --------
      @transaction = Transaction.new(transaction_params)

      if @transaction.transaction_type&.expense_category_id?
        @transaction.expense_account = @transaction.transaction_type.expense_category
        @transaction.fee = @transaction.transaction_type.expense_category.transaction_fee
      end

      if @transaction.save
        #-------- END (All of the above will be undone if not enough source)  --------
        source_amount = tran.summary.values[tran.source_account.code.downcase]
        raise NotEnoughSource.new "Insufficient funds on source account" if source_amount.negative?

        notice = "#{@transaction.actualized? ? '' : 'Draft'} Transaction was successfully created."
        redirect_to root_path, notice: notice
      else
        set_tran_types_for_frontend
        render :edit, status: :unprocessable_entity
      end

    end
  rescue NotEnoughSource => error
    @transaction.errors.add(:source_account_id, error.message)
  end
```

2021-10-05 07:21 UTC, Don-PhDev approved these changes

2021-10-05 08:02 UTC, rusbal approved these changes
🚢 :shipit:

2021-10-05 08:05 UTC, merged